Document: tbox
Title: Debian tbox Manual
Author: <insert document author here>
Abstract: This manual describes what tbox is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tbox/tbox.sgml.gz

Format: postscript
Files: /usr/share/doc/tbox/tbox.ps.gz

Format: text
Files: /usr/share/doc/tbox/tbox.text.gz

Format: HTML
Index: /usr/share/doc/tbox/html/index.html
Files: /usr/share/doc/tbox/html/*.html
